In [1]:
# Step 1: Imports
import tensorflow as tf
import sys
import os
sys.path.append(os.path.abspath('..'))

from utils.data_loader import DataGenerator
from utils.plot_metrics import plot_training_history

In [2]:
# Step 2: Data Loading
train_generator = DataGenerator(csv_file='../data/Regression/labels.csv', img_dir='../data/Regression/train')
val_generator = DataGenerator(csv_file='../data/Regression/labels.csv', img_dir='../data/Regression/valid')

print(train_generator.__len__())
print(val_generator.__len__())


79
20


In [5]:
# Paths to CSV and image directories for regression task
csv_file_path = '../data/Regression/labels.csv'  # CSV file containing image names and regression labels
train_img_dir = '../data/Regression/train'       # Directory containing training images
valid_img_dir = '../data/Regression/valid'       # Directory containing validation images

# Instantiate DataGenerator for training and validation for regression
train_generator = DataGenerator(
    csv_file=csv_file_path,
    img_dir=train_img_dir,
    batch_size=32,
    dim=(128, 128),
)

val_generator = DataGenerator(
    csv_file=csv_file_path,
    img_dir=valid_img_dir,
    batch_size=32,
    dim=(128, 128),
)

# Build a sample CNN model for regression
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(4, activation='linear')  # 4 regression outputs
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Train the model
history = model.fit(train_generator, validation_data=val_generator, epochs=10)


/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 7.2469 - mae: 1.0266

/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


79/79 ━━━━━━━━━━━━━━━━━━━━ 22s 269ms/step - loss: 7.1808 - mae: 1.0200 - val_loss: 0.1020 - val_mae: 0.2679
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 22s 281ms/step - loss: 0.1093 - mae: 0.2859 - val_loss: 0.0959 - val_mae: 0.2631
Epoch 3/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 23s 296ms/step - loss: 0.0890 - mae: 0.2580 - val_loss: 0.0880 - val_mae: 0.2523
Epoch 4/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 27s 339ms/step - loss: 0.0786 - mae: 0.2400 - val_loss: 0.0865 - val_mae: 0.2458
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 30s 382ms/step - loss: 0.0671 - mae: 0.2160 - val_loss: 0.0824 - val_mae: 0.2404
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 36s 461ms/step - loss: 0.0619 - mae: 0.2039 - val_loss: 0.0944 - val_mae: 0.2582
Epoch 7/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 34s 431ms/step - loss: 0.0576 - mae: 0.1969 - val_loss: 0.0805 - val_mae: 0.2370
Epoch 8/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 32s 409ms/step - loss: 0.0497 - mae: 0.1783 - val_loss: 0.0793 - val_mae: 0.2355
Epoch 9/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 31s 393ms/step - loss

In [16]:

# accuracy
model.evaluate(val_generator)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 0.0947 - mae: 0.2553


[0.09458959847688675, 0.25002947449684143]

In [17]:
# Step 6: Save Model
model.save('../model/usability_accessibility_regression_model.h5')
print("Model saved at ../model/usability_accessibility_regression_model.h5")


# Step 7: Load Model
loaded_model = tf.keras.models.load_model('../model/usability_accessibility_regression_model.h5')
print("Model loaded from ../model/usability_accessibility_regression_model.h5")

# Step 8: Evaluate Model
loaded_model.evaluate(val_generator)

# Step 9: Make Predictions
predictions = loaded_model.predict(val_generator)
print(predictions)






Model saved at ../model/usability_accessibility_regression_model.h5
Model loaded from ../model/usability_accessibility_regression_model.h5
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.1028 - mean_absolute_error: 0.2582
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step
[[ 9.7253591e-01  9.4667971e-01  1.0520681e+00  8.4305036e-01]
 [ 7.5452197e-01  7.4452943e-01  8.2332152e-01  6.5387744e-01]
 [-7.7600736e-04  3.2644577e-02  2.0541990e-02  1.8415898e-03]
 ...
 [-4.7352444e-02 -7.3118091e-02 -9.5483132e-02 -1.0930946e-01]
 [ 4.4444233e-01  4.1779926e-01  4.6299666e-01  3.9617491e-01]
 [ 7.1888262e-01  7.1352100e-01  7.8611851e-01  6.0960853e-01]]
