In [1]:
# Step 1: Imports
import tensorflow as tf
import sys
import os
sys.path.append(os.path.abspath('..'))

from utils.data_loader import DataGenerator
from utils.plot_metrics import plot_training_history

In [2]:
# Step 2: Data Loading
train_generator = DataGenerator(csv_file='../data/Regression/labels.csv', img_dir='../data/Regression/train')
val_generator = DataGenerator(csv_file='../data/Regression/labels.csv', img_dir='../data/Regression/valid')

print(train_generator.__len__())
print(val_generator.__len__())


79
20


In [3]:
# Paths to CSV and image directories for regression task
csv_file_path = '../data/Regression/labels.csv'  # CSV file containing image names and regression labels
train_img_dir = '../data/Regression/train'       # Directory containing training images
valid_img_dir = '../data/Regression/valid'       # Directory containing validation images

# Instantiate DataGenerator for training and validation for regression
train_generator = DataGenerator(
    csv_file=csv_file_path,
    img_dir=train_img_dir,
    batch_size=32,
    dim=(128, 128),
)

val_generator = DataGenerator(
    csv_file=csv_file_path,
    img_dir=valid_img_dir,
    batch_size=32,
    dim=(128, 128),
)

# Build a sample CNN model for regression
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(4, activation='linear')  # 4 regression outputs
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Train the model
history = model.fit(train_generator, validation_data=val_generator, epochs=10)


/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 3.2600 - mae: 0.8002

/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


79/79 ━━━━━━━━━━━━━━━━━━━━ 15s 176ms/step - loss: 3.2311 - mae: 0.7957 - val_loss: 0.1062 - val_mae: 0.2739
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 16s 200ms/step - loss: 0.0984 - mae: 0.2699 - val_loss: 0.0938 - val_mae: 0.2545
Epoch 3/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 17s 215ms/step - loss: 0.0812 - mae: 0.2396 - val_loss: 0.0893 - val_mae: 0.2516
Epoch 4/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 16s 206ms/step - loss: 0.0682 - mae: 0.2185 - val_loss: 0.0966 - val_mae: 0.2559
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 15s 189ms/step - loss: 0.0563 - mae: 0.1913 - val_loss: 0.0823 - val_mae: 0.2395
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 14s 176ms/step - loss: 0.0496 - mae: 0.1791 - val_loss: 0.0832 - val_mae: 0.2385
Epoch 7/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 165ms/step - loss: 0.0417 - mae: 0.1596 - val_loss: 0.0817 - val_mae: 0.2390
Epoch 8/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 15s 193ms/step - loss: 0.0366 - mae: 0.1505 - val_loss: 0.0811 - val_mae: 0.2364
Epoch 9/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 15s 186ms/step - loss

In [4]:

# accuracy
model.evaluate(val_generator)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - loss: 0.0963 - mae: 0.2559


[0.08957802504301071, 0.24434933066368103]

In [7]:
# Save the model using the recommended format
model.save('../model/usability_accessibility_regression_model.keras')
print("Model saved at ../model/usability_accessibility_regression_model.keras")



# Load the model with the recommended format
loaded_model = tf.keras.models.load_model('../model/usability_accessibility_regression_model.keras')
print("Model loaded from ../model/usability_accessibility_regression_model.keras")

# Evaluate the model
loaded_model.compile(optimizer='adam', loss='mse', metrics=['mae'])  # Recompile if necessary
loaded_model.evaluate(val_generator)

# efficiently make predictions

predictions = loaded_model.predict(val_generator)
print(predictions)







Model saved at ../model/usability_accessibility_regression_model.keras
Model loaded from ../model/usability_accessibility_regression_model.keras


/Users/defaultuser1/Desktop/Mobile_Detect/.venv/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 10 variables whereas the saved optimizer has 18 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0891 - mae: 0.2386
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step
[[0.14282498 0.11507619 0.1532537  0.12703645]
 [0.7917674  0.7362321  0.82774824 0.62534666]
 [0.6921976  0.61921763 0.71292245 0.553695  ]
 ...
 [0.68400365 0.60201436 0.6015418  0.5085323 ]
 [0.5599687  0.5036945  0.54285794 0.44537902]
 [0.34380573 0.30375975 0.35621005 0.28308398]]
